### ISSUE TITLE
Problemas com o "enconding" do código:

### ISSUE THREAD

**Issue by ilmoruuu** [Pedro-RGS/jsp-servlet-baseapp#1]
## Descrição
Padronizar a codificação dos arquivos para UTF-8 no projeto. O problema atual envolve caracteres especiais (acentos e símbolos) que estão sendo exibidos incorretamente na IDE, sugerindo um conflito de encoding entre diferentes ambientes ou editores.

## Nome
Murilo Gonçalves de Lucena

## O que acontece
Ao abrir um arquivo Java na IntelliJ, uma mensagem de erro é exibida:
"The file was loaded in a wrong encoding: 'UTF-8'".
Alguns comentários e textos no código apresentam caracteres quebrados (ex.: "requisi��o" em vez de "requisição").

## O Que é esperado
O arquivo deve ser interpretado corretamente utilizando UTF-8, com todos os caracteres especiais exibidos normalmente.
O projeto inteiro deve ser configurado para evitar problemas de codificação em futuras edições.
Mensagens de Erro
"The file was loaded in a wrong encoding: 'UTF-8'"
Exibição incorreta de caracteres especiais no código.

## Foto/Vídeo comprovatório
![image](https://github.com/user-attachments/assets/4eb3d394-8123-4b07-9af6-5ef6099ebd55)

## Passos para a reprodução
Abra o projeto no IntelliJ IDEA.
Acesse o arquivo ListUsersServlet.java.
Observe que uma mensagem de erro é exibida indicando problema de encoding.
Verifique o conteúdo do arquivo e note que alguns caracteres aparecem corrompidos (ex.: "requisi��o").

**Comment by paulabeatrizz** [comment]
Acho que pra esse momento pode ser um reload do arquivo em 'ISO-8859-1', para conseguir apenas visualizar o arquivo.

**Comment by Pedro-RGS** [comment]
Não alterei o padrão, tentei alterar apenas os arquivos necessários

**Comment by ilmoruuu** [comment]
É interessante fazer o reload para "ISO-8859-1", esse problema se deu ao existirem arquivos com "ç" ou "ã", **aparentemente** esse reload não prejudica o funcionamento, tem a mesma aplicação de um "refrator"
