### ISSUE TITLE
Demandas Principais

### ISSUE THREAD

**Issue by paulabeatrizz** [Pedro-RGS/jsp-servlet-baseapp#2]
- [x] Linkar a Máquina do Cliente com o serviço render.com

- [ ] Instalar DB na máquina do cliente

- [ ] GitHub Actions/Docker

**Comment by ilmoruuu** [comment]
Olá Paula!

Essas são as suas demandas realizadas? Até o momento realizei as seguintes:
- Escolha do líder da equipe (Escolhemos Pedro)
- Atualizar o ".gitignore" (A pasta ".idea" e derivados são ignorados)
- Montar a Estrutura de Branches (Cada desenvolvedor criou a sua e criei a "development")
- Fazer o Script de Teste do GitHub Actions (Agora os testes são automatizados)

Você pode me confirmar se esses estão pendentes ou resolvidos?

**Comment by paulabeatrizz** [comment]
Olá Murilo, estão pendentes!
Listei os seguintes para termos controle do nosso andamento!
 
Minhas demandas realizadas são:
- Escolha do líder da equipe (Pedro)
- Atualizar o ".gitignore" 
- Montar a Estrutura de Branches

**Comment by Pedro-RGS** [comment]
Até agora:
- Escolha do líder
- Atualizar o .gitignore
- montar a estrutra de branches
Em andamento:
- Fazer o arquivo do github actions
- Fazer deploy da aplicação dentro do Render
Motivo:
Dificuldade em fazer essas tarefas

**Comment by ilmoruuu** [comment]
Perfeito! Fico muito orgulhoso com o resultado até o momento!
Você podem realizar o merge com minha branch para contemplarem os quesitos do ".gitignore" e do Actions!

Atenciosamente, 
Murilo Lucena

**Comment by paulabeatrizz** [comment]
Creio que precisamos dar merge de nossas branches no development e consertar possíveis erros!

**Comment by ilmoruuu** [comment]
Justo, vamos!

**Comment by Pedro-RGS** [comment]
Lembrem de adicionar ao README as demandas realizadas hoje por vocês

**Comment by Pedro-RGS** [comment]
se tudo estiver correto, podem subir para a main

**Comment by ilmoruuu** [comment]
Vou mesclar com a de desenvolvimento, testar e se tudo der certo, posteriormente pode ir pra main. Aviso em breve!

**Comment by paulabeatrizz** [comment]
Development está atualizada com as alterações da minha branch.

**Comment by paulabeatrizz** [comment]
@ilmoruuu Por que o ReadMe está no .gitignore na branch development?

**Comment by Pedro-RGS** [comment]
@ilmoruuu Dá git pull na branch pedro, ela tem o código atualizado e devidamente editado com as demandas de cada desenvolvedor advindo das branches pedro e paula, necessitando apenas do seu nome no arquivo "about.jsp"

**Comment by paulabeatrizz** [comment]
@ilmoruuu conseguiu realizar a tarefa anterior?

**Comment by ilmoruuu** [comment]
Atualizando minhas demandas realizadas:
- Escolha do líder da equipe (Escolhemos Pedro)
- Atualizar o ".gitignore" (A pasta ".idea" e derivados são ignorados)
- Montar a Estrutura de Branches (Cada desenvolvedor criou a sua e criei a "development")
- Fazer o Script de Teste do GitHub Actions (Agora os testes são automatizados)
- Instalar DB na máquina do Cliente (Ainda em testes)
- Atualizei a página "Sobre" (Coloquei meu nome lá!)

**Comment by paulabeatrizz** [comment]
@Pedro-RGS por favor nos atualize assim que concluir! ou se precisar de algo.
