### ISSUE TITLE
Deploy da aplicação no Render

### ISSUE THREAD

**Issue by Pedro-RGS** [Pedro-RGS/jsp-servlet-baseapp#3]
Não consigo realizar o deploy da aplicação e também não sei quais são as variáveis de ambiente
Estou tentando colocar estas variáveis encontradas no arquivo docker-compose.dev.yml
![image](https://github.com/user-attachments/assets/952ff461-15a6-444c-9170-a4350756ea1a)

**Comment by ilmoruuu** [comment]
Oi Pedro! Posso tentar ver o que está acontecendo! Estou indo agora para o seu código!

**Comment by ilmoruuu** [comment]
Amigo, você tá tentando usar o Docker, fiz os testes aqui e continua dando erro, dá uma olhada nos Actions! Tá reclamando do teu JDK (que tá 11)
![image](https://github.com/user-attachments/assets/ba07ef8e-25e0-47f1-a9cb-cacd5c7ca136)

**Comment by Pedro-RGS** [comment]
@ilmoruuu dei merge com a duas branches e vou dar push na branch pedro, peço que realize a modificação no arquivo "about.jsp"

**Comment by Pedro-RGS** [comment]
@ilmoruuu quanto ao docker, estou tentando fazer o github actions usando ele, mas está dando tudo errado. Vou remové-lo

**Comment by ilmoruuu** [comment]
Acho que todos estamos utilizando o JDK 21, naquele arquivo do Actions tenta colocar 21

**Comment by paulabeatrizz** [comment]
Aguardo atualizações!

**Comment by ilmoruuu** [comment]
@Pedro-RGS tu já realizou a instalação do DB na máquina do cliente, pois estou tentando aqui.

**Comment by Pedro-RGS** [comment]
opa, Murilo

Não tenho ideia de como fazer isso, apenas consegui fazer o deploy da aplicação através do render.
Acredito que o Render possui o seu próprio banco de dados.

**Comment by ilmoruuu** [comment]
Conseguiu? Perfeito! Acho que estou conseguindo aqui fazer o DB!
Ficou confuso pra mim a explicação dada pelo Professor.

**Comment by Pedro-RGS** [comment]
Nõs não fizemos os testes automatizados ainda, vou retirá-los do readme da branch pedro

**Comment by paulabeatrizz** [comment]
Link da página funciona em minha máquina!

**Comment by ilmoruuu** [comment]
coloquei em minha branch a tentativa da instalação do db, não consegui testar ainda.

**Comment by ilmoruuu** [comment]
@paulabeatrizz perfeito! Menos um empecilho! Vai dar certo!

**Comment by Pedro-RGS** [comment]
gente, faltam 5 minutos. Vou fazer merge das branches, corrigir erros e dar push para a main

**Comment by ilmoruuu** [comment]
Certo!

**Comment by ilmoruuu** [comment]
Estou orgulhoso do nosso trabalho, estamos fazendo nosso melhor!
